Transform: AWS::Serverless-2016-10-31
Metadata:
  AWS::ServerlessRepo::Application:
    Name: alibaba-dingding-lambda-layer
    Description: Ali Dingding Lambda Layer - Produced by Niko Feng(nikosheng@gmail.com)
    Author: nikosheng
    SpdxLicenseId: Apache-2.0
    LicenseUrl: s3://aws-nikofeng-serverless-application-repo/3b83ef96387f14655fc854ddc3c6bd57
    ReadmeUrl: s3://aws-nikofeng-serverless-application-repo/f3e864fe41e5b920a827fdbcc74412fb
    Labels:
    - alibaba
    - dingding
    - lambda-layer
    HomePageUrl: https://github.com/nikosheng/wechat-lambda-layer-sam
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/nikosheng/wechat-lambda-layer-sam
Resources:
  DingdingLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: DingdingLayer
      Description: v.1.0.0
      ContentUri: s3://aws-nikofeng-serverless-application-repo/61cd5dd3daf9373ca80d2b7b4be7c5af
      CompatibleRuntimes:
      - python3.6
      - python3.7
      - python3.8
Outputs:
  DingdingLambdaLayer:
    Value:
      Ref: DingdingLambdaLayer
