Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: alibaba-dingding-lambda-layer
    Description: Ali Dingding Lambda Layer - Produced by Niko Feng(nikosheng@gmail.com)
    Author: nikosheng
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    Labels: ['alibaba', 'dingding', 'lambda-layer']
    HomePageUrl: https://github.com/nikosheng/alibaba-dingding-lambda-layer
    SemanticVersion: 1.0.1
    SourceCodeUrl: https://github.com/nikosheng/alibaba-dingding-lambda-layer

Resources:
  DingdingLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: DingdingLayer
      Description: v.1.0.1
      ContentUri: layer/
      CompatibleRuntimes:
      - python3.6
      - python3.7
      - python3.8

Outputs:
  DingdingLambdaLayer:
    Value:
      Ref: DingdingLambdaLayer